# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

# More information at this link: https://docs.coderabbit.ai/configure-coderabbit
reviews:
  auto_review:
    base_branches:
      - develop-postgres
      - develop
      - main
  poem: false
  profile: "assertive"
  request_changes_workflow: true

