coverage:
  status:
    project:
      default:
        target: 57%
    patch:
      default:
        # This target applies only to installation scripts to ensure high quality for this critical component.
        # Other files fall under the project-wide target.
        target: 95%
        paths:
          - "scripts/setup/**"
          - "scripts/dbManagement/**"
          - "setup.ts"
