version: "3.8"
services:
  mongo:
    # No light weight image is available for mongo
    image: mongo:8.0.4
    container_name: mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./scripts/docker/init-mongo.sh:/init-mongo.sh
    networks:
      - talawa-network
    entrypoint: ["/bin/bash", "/init-mongo.sh"]

  redis-stack-server:
    image: redis:8.0-M02-alpine
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    volumes:
      - redis-data:/data/redis
    networks:
      - talawa-network

  minio:
    # No light weight image is available
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
    volumes:
      - minio-data:/data
    networks:
      - talawa-network

  talawa-api-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: talawa-api-prod
    ports:
      - "4000:4000"
    volumes:
      - /usr/src/app/node_modules
      - ./scripts/docker/init-data-import.sh:/init-data-import.sh
    depends_on:
      mongo:
        condition: service_healthy
      redis-stack-server:
        condition: service_started
      minio:
        condition: service_started
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017/talawa-dev?replicaSet=rs0
      - NODE_ENV=development
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
    entrypoint: ["/bin/bash", "/init-data-import.sh"]
    networks:
      - talawa-network

  caddy:
    image: caddy/caddy:2.9.1-alpine
    container_name: caddy-service
    restart: unless-stopped
    ports:
      - "9080:9080"
      - "9443:9443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/graphql"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
    networks:
      - talawa-network

volumes:
  redis-data:
  minio-data:
  mongo_data:
  caddy_data:
  caddy_config:

networks:
  talawa-network:
