# Stage 1: Build stage
FROM node:22.13.1 

WORKDIR /usr/src/app

# Copy only necessary files for dependency installation
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source files (exclude .dockerignore content)
COPY . .

# Expose the application port
EXPOSE 4000

# Start the application
CMD ["npm", "run", "dev"]
