# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0'  # required by bashcov 3.x

gem 'bashcov', '~> 3.1'
# Use patched simplecov from vendor (see CI) so we can use simplecov-html 0.12.3 on Ruby 3.2
gem 'simplecov', path: 'vendor/simplecov'
gem 'simplecov-html', '0.12.3'  # 0.11.0 requires Ruby ~> 2.4; 0.12.3 supports Ruby 3.2
gem 'simplecov-cobertura', '~> 2.1'
