services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
  
  redis-stack-server:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT:-4000}:4000"
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - mongodb
      - redis-stack-server
    environment:
      - MONGO_DB_URL=mongodb://mongodb:27017
      - REDIS_HOST=redis-stack-server
      - REDIS_PORT=6379

volumes:
  mongodb-data:
  redis-data:
