#!/bin/bash

# Purpose: Renew SSL certificates generated by Certbot
# These certificates are required to be renewed every 90 days.
# This script will be used to create a cronjob for automatic renewal.

# Renew the certificates
certbot renew

