#!/bin/bash

# Purpose: Renew SSL certificates generated by Certbot
# These certificates are required to be renewed every 90 days.
# This script will be used to create a cronjob for automatic renewal.

# Renew the certificates
certbot renew

# Set permissions to 700 for the script
chmod 700 "$0"

# Set ownership to talawa-api user
chown talawa-api "$0"
