name: Deploy to AWS EC2

on:
  push:
    branches:
      - deployment
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Execute remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 200m
        script: |
          cd talawa-api
          git pull origin
          docker-compose down
          docker-compose up -d --build

