name: Deploy to Cloud VPS

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Execute remote ssh commands 
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.API_DEMO_HOST }}
        username: ${{ secrets.API_DEMO_USERNAME }}
        key: ${{ secrets.API_DEMO_SSH_KEY }}
        port: ${{ secrets.API_DEMO_PORT }}
        command_timeout: 30m
        script: |
          cd develop 
          cd talawa-api
          git checkout develop
          git pull origin
          docker-compose down
          docker-compose up -d --build

