name: Deploy to AWS EC2

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Execute remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git clone https://github.com/PalisadoesFoundation/talawa-api.git
          cd talawa-api
          sudo apt-get update
          sudo docker system prune -a -f
          sudo docker-compose up --build -d
          cd ..
          sudo rm -fr talawa-api/

