name: Expose Server with Docker Compose for Updating Documentation
on:
  push:
    branches: [ auto ]
  workflow_dispatch:

jobs:
  Schema_Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start the server in a Docker container
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yml"

    - name: Wait for server to start
      run: sleep 10

    - name: Generate Schema Documentation
      run: npm run schema

    - name: Commit the changes to Schema Documentation (if any)
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update Schema Documentation"