##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should
# be placed in this file
#
##############################################################################
##############################################################################

name: Generate Schema Documentation
on:
  push:
    branches:
      - '**'
                
jobs:
  Schema-Generation:
    name: Generate Schema
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 27017:27017
    env:
      MONGO_DB_URL: mongodb://localhost:27017/talawa-test-db
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Generate Access Token Secret
        run: echo "ACCESS_TOKEN_SECRET=$(openssl rand -hex 32)" >> $GITHUB_ENV
        
      - name: Generate Refresh Token Secret
        run: echo "REFRESH_TOKEN_SECRET=$(openssl rand -hex 32)" >> $GITHUB_ENV

      - name: Set up Node.js 14.X
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Start the development server in detach mode
        run: |
          npm run dev &
          echo "Development server started..."

      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 10s

      - name: Generate the documentation
        run: npm run schema

      - name: Commit the changes to Schema Documentation (if any)
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update Schema Documentation"
