name: Copy Docs to Talawa Docs

on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  copy-docs-to-talawa-docs:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/automated-docs'
    # needs: Generate-Documentation
    steps:
    - uses: actions/checkout@v3
    - uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
      env:
        API_TOKEN_GITHUB: ${{secrets.TALAWA_DOCS_SYNC}}    
      with:
        source_file: 'talawa-api-docs/'
        destination_repo: 'PalisadoesFoundation/talawa-docs'
        destination_branch: 'develop'
        destination_folder: 'docs/'
        user_email: '${{env.email}}'
        user_name: '${{github.actor}}'
        commit_message: 'Talawa API docs updated'
