import "./Advertisement/index";
import "./AdvertisementAttachment/index";
import "./AuthenticationPayload";
import "./Mutation/index";
import "./Organization/index";
import "./Query/index";
import "./Subscription/index";
import "./Tag/index";
import "./User/index";
